### PR TITLE
handle UnicodeDecodeError in path

### PR DESCRIPTION
**Pull request by jaypz**

### CODE REVIEW

**Comment by jaypz** [comment]
DEVTOOLS-1142

**Comment by kneblett** [comment]
Is this PR still valid even though the ticket is closed?

**Comment by jaypz** [comment]
@kneblett yeah still need someone to approve it to merge - this is to reflect a change that was made on the live running code (not ideal); this is a fork of an external project

**Review by owenstone — APPROVED** [review]
LGTM

**Pull request merged**
